data: 'shrec_skeleton'
data_param:
  train_data_param:
    data_path: /home/xzzit/DSTA-summer2023/Data/v3/summer_train_skeleton.pkl
    label_path: /home/xzzit/DSTA-summer2023/Data/v3/summer_train_label.pkl
    random_choose: True
    center_choose: False
    window_size: 52
    final_size: 36
    num_skip_frame:
    decouple_spatial: False
  val_data_param:
    data_path: /home/xzzit/DSTA-summer2023/Data/v3/summer_val_skeleton.pkl
    label_path: /home/xzzit/DSTA-summer2023/Data/v3/summer_val_label.pkl
    random_choose: False
    center_choose: True
    window_size: 52
    final_size: 36
    num_skip_frame:
    decouple_spatial: False

# model
model: 'dstanet'
class_num: 11
model_param:
  num_point: 12
  num_frame: 36
  num_subset: 2
  num_person: 1
  glo_reg_s: True
  att_s: True
  glo_reg_t: False
  att_t: True
  dropout: 0
  attentiondrop: 0
  dropout2d: 0
  config: [ [64, 64, 16, 1], [64, 64, 16, 1],
            [64, 128, 32, 2], [128, 128, 32, 1],
            [128, 256, 64, 2], [256, 256, 64, 1],
            [256, 256, 64, 1], [256, 256, 64, 1],
  ]
  use_spatial_att: True
  use_temporal_att: True
  use_pet: True
  use_pes: True


train: 'classify'
mode: 'train_val'
loss: 'cross_entropy'
batch_size: 32
worker: 16
pin_memory: False
num_epoch_per_save: 100
model_saved_name: './work_dir/summer23/dstanet_inference'
last_model:
pre_trained_model: '/home/xzzit/DSTA-summer2023/work_dir/summer23/dstanet_v3_36-latest.state'
ignore_weights: []
label_smoothing_num: 0
mix_up_num: 0
device_id: [0]
cuda_visible_device: '0'
debug: False

# lr
lr_scheduler: 'reduce_by_epoch'
lr_param:
  step: [60, 90]
  gamma: 0.1
warm_up_epoch: 5
max_epoch: 120
lr: 0.1
wd: 0.0005
lr_decay_ratio: 0.1
lr_multi_keys: []

# optimizer
optimizer: 'sgd_nev'
freeze_keys: []

