data: 'skeleton'
data_param:
  train_data_param:
    data_path: /home/lshi/Database/dhg_hand_shrec/train_skeleton_ddnet.pkl
    label_path: /home/lshi/Database/dhg_hand_shrec/train_label_ddnet_28.pkl
    random_choose: True
    center_choose: False
    window_size: 120
    final_size: 8
    random_move: [10, 10, 0.2]
    num_skip_frame: 1
    #    decouple_spatial: True
    edges: [[0, 1],
            [1, 2], [2, 3], [3, 4], [4, 5],
            [1, 6], [6, 7], [7, 8], [8, 9],
            [1, 10], [10, 11], [11, 12], [12, 13],
            [1, 14], [14, 15], [15, 16], [16, 17],
            [1, 18], [18, 19], [19, 20], [20, 21]]
  val_data_param:
    data_path: /home/lshi/Database/dhg_hand_shrec/val_skeleton_ddnet.pkl
    label_path: /home/lshi/Database/dhg_hand_shrec/val_label_ddnet_28.pkl
    random_choose: False
    center_choose: True
    window_size: 120
    final_size: 8
    num_skip_frame: 1
    #    decouple_spatial: True
    edges: [[0, 1],
            [1, 2], [2, 3], [3, 4], [4, 5],
            [1, 6], [6, 7], [7, 8], [8, 9],
            [1, 10], [10, 11], [11, 12], [12, 13],
            [1, 14], [14, 15], [15, 16], [16, 17],
            [1, 18], [18, 19], [19, 20], [20, 21]]

# model
model: 'dstanet'
class_num: 28
model_param:
  num_point: 22
  num_frame: 8
  num_subset: 8
  num_person: 1
  glo_reg_s: True
  att_s: True
  glo_reg_t: True
  att_t: True
  dropout: 0.2
  attentiondrop: 0
  dropout2d: 0
  config: [[128, 128, 32, 1]]
  use_spatial_att: True
  use_temporal_att: True


train: 'classify'
mode: 'train_val'
loss: 'cross_entropy'
batch_size: 32
worker: 32
pin_memory: False
num_epoch_per_save: 1
model_saved_name: './agcnv2/val/stagcnattention_drop02_1004050_8_glo_reg_2s_glo_reg_2t_warm5_init1_nog_tan_lrelu_v1-28'
last_model: './agcnv2/dhg28/stagcnattention_drop02_1004050_8_glo_reg_2s_glo_reg_2t_warm5_init1_nog_tan_lrelu_v1-27-1708.state'
pre_trained_model:
ignore_weights: []
label_smoothing_num: 0
mix_up_num: 0
device_id: [0]
cuda_visible_device: '4'
debug: False

# lr
lr_scheduler: 'reduce_by_epoch'
lr_param:
  step: [100, 140]
  gamma: 0.1
#  lr_patience: 20
#  lr_threshold: 0.0001
#  lr_delay: 10
warm_up_epoch: 5
max_epoch: 150
lr: 0.001
wd: 0.0005
lr_decay_ratio: 0.1
lr_multi_keys: []

# optimizer
optimizer: 'adam'
freeze_keys: []

