data: 'rgbgulp'
data_param:
  train_data_param:
    data_path: /home/lshi/Database/ntu_rgb/gulp_crop_square_big/train
    label_path: /home/lshi/Database/ntu_60/xsub/train_label.pkl
    resize_shape: [20, 256, 256]
    final_shape: [16, 224, 224]
    mean: [0.5, 0.5, 0.5]
    use_flip: [0, 0, 0]
  val_data_param:
    data_path: /home/lshi/Database/ntu_rgb/gulp_crop_square_big/val
    label_path: /home/lshi/Database/ntu_60/xsub/val_label.pkl
    resize_shape: [20, 256, 256]
    final_shape: [16, 224, 224]
    mean: [0.5, 0.5, 0.5]
    use_flip: [0, 0, 0]

# model
model: 'resnext101'
class_num: 60
model_param:

train: 'classify'
mode: 'train_val'
loss: 'cross_entropy'
batch_size: 16
worker: 16
pin_memory: False
num_epoch_per_save: 5
model_saved_name: './work_dir/ntu60/resnext_101520'
last_model:
pre_trained_model: '/home/lshi/Model/3dmodel/kinetics_resnext101_64120-408606.state'
ignore_weights: ['fc']
label_smoothing_num: 0
mix_up_num: 0
device_id: [0, 1, 2, 3]
cuda_visible_device: '1, 2, 3, 4'
debug: False

# lr
lr_scheduler: 'reduce_by_epoch'
lr_param:
  step: [10, 15]
#  lr_patience: 10
#  lr_threshold: 0.0001
#  lr_delay: 0
warm_up_epoch: 5
max_epoch: 20
lr: 0.01
wd: 0.0005
lr_decay_ratio: 0.1
lr_multi_keys: []

# optimizer
optimizer: 'sgd_nev'
freeze_keys: []

